name: tflite_demo
description: A new Flutter project.

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.2.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  tflite: ^1.0.4
  image_picker: ^0.6.1+8
  image: ^2.1.4

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:
  fonts:
    - family: Titania
      fonts:
        - asset: assets/fonts/Titania-Regular.ttf
    - family: PlantinMTProRg
      fonts:
        - asset: assets/fonts/PlantinMTProRg.TTF
    - family: Syntha
      fonts:
        - asset: assets/fonts/Syntha.ttf
    - family: Digitechno
      fonts:
        - asset: assets/fonts/Digitechno-FreeVersion.ttf
  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true
  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/tflite/ssd_mobilenet.tflite
    - assets/tflite/ssd_mobilenet.txt
    - assets/tflite/yolov2_tiny.tflite
    - assets/tflite/yolov2_tiny.txt
    - assets/tflite/orezmodel.tflite
    - assets/tflite/labels.txt
    - assets/images/paddy.png
    - assets/images/drone.png
    - assets/images/no_image.png
    - assets/images/paddy1.jpg
    - assets/images/paddy2.jpg
    - assets/images/paddy3.jpg
    - assets/images/paddy4.jpg
    - assets/images/paddy5.jpg
    - assets/images/paddy6.jpg
    - assets/images/paddy7.jpg
    - assets/images/paddy8.jpg
    - assets/images/paddy9.jpg
    - assets/images/paddy10.jpg
    - assets/images/paddy11.jpg
    - assets/images/paddy12.jpg
    - assets/images/paddy13.jpg
    - assets/images/paddy14.jpg
    - assets/images/paddy15.jpg
    - assets/images/paddy16.jpg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.
  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages
  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
